# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ForumBundle\:
        resource: '../../src/ForumBundle/*'
        exclude: '../../src/ForumBundle/{Entity,Repository,Tests}'

    ForumBundle\Controller\:
        resource: '../../src/ForumBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    app.menu_builder:
        class: ForumBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
        - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
    forum.form.registration:
        class: ForumBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: forum_user_registration }